services:
    avro_case.twig.extension:
        class: TripleHelix\CaseBundle\Twig\Extension\CaseExtension
        tags:
            -  { name: twig.extension } 
        arguments: ["@avro_case.converter"]
